<?php

namespace Database\Seeders;

use App\Models\District;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    $districts = [
      [
        'name' => 'Bengkayang',
        'province_id' => '5',
        'region' => 'Kabupaten',
        'long' => '109.66393',
        'lat' => '1.06911',
      ],
      [
        'name' => 'Kapuas Hulu',
        'province_id' => '5',
        'region' => 'Kabupaten',
        'long' => '112.76667',
        'lat' => '0.81667',
      ],
      [
        'name' => 'Kayong Utara',
        'province_id' => '5',
        'region' => 'Kabupaten',
        'long' => '110.79781',
        'lat' => '-1.43711',
      ],
      [
        'name' => 'Ketapang',
        'province_id' => '5',
        'region' => 'Kabupaten',
        'long' => '110.5',
        'lat' => '-1.58333',
      ],
      [
        'name' => 'Kubu Raya',
        'province_id' => '5',
        'region' => 'Kabupaten',
        'long' => '109.33731',
        'lat' => '0.01637',
      ],
      [
        'name' => 'Landak',
        'province_id' => '5',
        'region' => 'Kabupaten',
        'long' => '109.75917',
        'lat' => '0.42373',
      ],
      [
        'name' => 'Melawi',
        'province_id' => '5',
        'region' => 'Kabupaten',
        'long' => '111.6981',
        'lat' => '-0.3361',
      ],
      [
        'name' => 'Mempawah',
        'province_id' => '5',
        'region' => 'Kabupaten',
        'long' => '109.16667',
        'lat' => '0.25',
      ],
      [
        'name' => 'Sambas',
        'province_id' => '5',
        'region' => 'Kabupaten',
        'long' => '109.33333',
        'lat' => '1.41667',
      ],
      [
        'name' => 'Sanggau',
        'province_id' => '5',
        'region' => 'Kabupaten',
        'long' => '110.6',
        'lat' => '0.1',
      ],
      [
        'name' => 'Sekadau',
        'province_id' => '5',
        'region' => 'Kabupaten',
        'long' => '110.95066',
        'lat' => '0.03485',
      ],
      [
        'name' => 'Sintang',
        'province_id' => '5',
        'region' => 'Kabupaten',
        'long' => '111.4981',
        'lat' => '0.0681',
      ],
      [
        'name' => 'Pontianak',
        'province_id' => '5',
        'region' => 'Kota',
        'long' => '109.3414',
        'lat' => '-0.0206',
      ],
      [
        'name' => 'Singkawang',
        'province_id' => '5',
        'region' => 'Kota',
        'long' => '108.9833',
        'lat' => '0.9',
      ],
      [
        'name' => 'Barito Selatan',
        'province_id' => '3',
        'region' => 'Kabupaten',
        'long' => '114.73333',
        'lat' => '-1.86667',
      ],
      [
        'name' => 'Barito Timur',
        'province_id' => '3',
        'region' => 'Kabupaten',
        'long' => '115.1',
        'lat' => '-1.93333',
      ],
      [
        'name' => 'Barito Utara',
        'province_id' => '3',
        'region' => 'Kabupaten',
        'long' => '115.1',
        'lat' => '-0.98333',
      ],
      [
        'name' => 'Gunung Mas',
        'province_id' => '3',
        'region' => 'Kabupaten',
        'long' => '113.5',
        'lat' => '-0.95',
      ],
      [
        'name' => 'Kapuas',
        'province_id' => '3',
        'region' => 'Kabupaten',
        'long' => '114.38',
        'lat' => '-3.0',
      ],
      [
        'name' => 'Katingan',
        'province_id' => '3',
        'region' => 'Kabupaten',
        'long' => '113.4',
        'lat' => '-2.06667',
      ],
      [
        'name' => 'Kotawaringin Barat',
        'province_id' => '3',
        'region' => 'Kabupaten',
        'long' => '111.73333',
        'lat' => '-2.4',
      ],
      [
        'name' => 'Kotawaringin Timur',
        'province_id' => '3',
        'region' => 'Kabupaten',
        'long' => '112.75',
        'lat' => '-2.08333',
      ],
      [
        'name' => 'Lamandau',
        'province_id' => '3',
        'region' => 'Kabupaten',
        'long' => '111.2869',
        'lat' => '-1.83828',
      ],
      [
        'name' => 'Murung Raya',
        'province_id' => '3',
        'region' => 'Kabupaten',
        'long' => '115.1333',
        'lat' => '-1.4083',
      ],
      [
        'name' => 'Pulang Pisau',
        'province_id' => '3',
        'region' => 'Kabupaten',
        'long' => '113.8623',
        'lat' => '-3.11858',
      ],
      [
        'name' => 'Seruyan',
        'province_id' => '3',
        'region' => 'Kabupaten',
        'long' => '112.25',
        'lat' => '-2.33333',
      ],
      [
        'name' => 'Sukamara',
        'province_id' => '3',
        'region' => 'Kabupaten',
        'long' => '111.23681',
        'lat' => '-2.62675',
      ],
      [
        'name' => 'Palangka Raya',
        'province_id' => '3',
        'region' => 'Kota',
        'long' => '113.92',
        'lat' => '-2.21',
      ],
      [
        'name' => 'Balangan',
        'province_id' => '4',
        'region' => 'Kabupaten',
        'long' => '115.47051359',
        'lat' => '-2.36400077',
      ],
      [
        'name' => 'Banjar',
        'province_id' => '4',
        'region' => 'Kabupaten',
        'long' => '114.84854166',
        'lat' => '-3.40813134',
      ],
      [
        'name' => 'Barito Kuala',
        'province_id' => '4',
        'region' => 'Kabupaten',
        'long' => '114.76677877',
        'lat' => '-2.98114305',
      ],
      [
        'name' => 'Hulu Sungai Selatan',
        'province_id' => '4',
        'region' => 'Kabupaten',
        'long' => '115.26591976',
        'lat' => '-2.78667006',
      ],
      [
        'name' => 'Hulu Sungai Tengah',
        'province_id' => '4',
        'region' => 'Kabupaten',
        'long' => '115.38517139',
        'lat' => '-2.58465575',
      ],
      [
        'name' => 'Hulu Sungai Utara',
        'province_id' => '4',
        'region' => 'Kabupaten',
        'long' => '115.25427967',
        'lat' => '-2.41928439',
      ],
      [
        'name' => 'Kotabaru',
        'province_id' => '4',
        'region' => 'Kabupaten',
        'long' => '116.0',
        'lat' => '-3.0',
      ],
      [
        'name' => 'Tabalong',
        'province_id' => '4',
        'region' => 'Kabupaten',
        'long' => '115.38221327',
        'lat' => '-2.16473568',
      ],
      [
        'name' => 'Tanah Bumbu',
        'province_id' => '4',
        'region' => 'Kabupaten',
        'long' => '115.9479384',
        'lat' => '-3.48363391',
      ],
      [
        'name' => 'Tanah Laut',
        'province_id' => '4',
        'region' => 'Kabupaten',
        'long' => '114.78259338',
        'lat' => '-3.79973924',
      ],
      [
        'name' => 'Tapin',
        'province_id' => '4',
        'region' => 'Kabupaten',
        'long' => '115.15668238',
        'lat' => '-2.9308974',
      ],
      [
        'name' => 'Banjarbaru',
        'province_id' => '4',
        'region' => 'Kota',
        'long' => '114.83088092',
        'lat' => '-3.43890306',
      ],
      [
        'name' => 'Banjarmasin',
        'province_id' => '4',
        'region' => 'Kota',
        'long' => '114.59225374',
        'lat' => '-3.31442947',
      ],
      [
        'name' => 'Berau',
        'province_id' => '2',
        'region' => 'Kabupaten',
        'long' => '117.3',
        'lat' => '2.0',
      ],
      [
        'name' => 'Kutai Barat',
        'province_id' => '2',
        'region' => 'Kabupaten',
        'long' => '115.51575',
        'lat' => '-0.59417',
      ],
      [
        'name' => 'Kutai Kartanegara',
        'province_id' => '2',
        'region' => 'Kabupaten',
        'long' => '116.98139',
        'lat' => '-0.44019',
      ],
      [
        'name' => 'Kutai Timur',
        'province_id' => '2',
        'region' => 'Kabupaten',
        'long' => '117.83112',
        'lat' => '1.03769',
      ],
      [
        'name' => 'Mahakam Ulu',
        'province_id' => '2',
        'region' => 'Kabupaten',
        'long' => '115.28',
        'lat' => '0.5',
      ],
      [
        'name' => 'Paser',
        'province_id' => '2',
        'region' => 'Kabupaten',
        'long' => '116.23535',
        'lat' => '-1.43517',
      ],
      [
        'name' => 'Penajam Paser Utara',
        'province_id' => '2',
        'region' => 'Kabupaten',
        'long' => '116.513796',
        'lat' => '-1.291709',
      ],
      [
        'name' => 'Balikpapan',
        'province_id' => '2',
        'region' => 'Kota',
        'long' => '116.9031',
        'lat' => '-1.1489',
      ],
      [
        'name' => 'Bontang',
        'province_id' => '2',
        'region' => 'Kota',
        'long' => '117.5',
        'lat' => '0.13',
      ],
      [
        'name' => 'Samarinda',
        'province_id' => '2',
        'region' => 'Kota',
        'long' => '117.1536',
        'lat' => '-0.5022',
      ],
      [
        'name' => 'Bulungan',
        'province_id' => '1',
        'region' => 'Kabupaten',
        'long' => '117.16667',
        'lat' => '3.0',
      ],
      [
        'name' => 'Malinau',
        'province_id' => '1',
        'region' => 'Kabupaten',
        'long' => '115.6833',
        'lat' => '2.45',
      ],
      [
        'name' => 'Nunukan',
        'province_id' => '1',
        'region' => 'Kabupaten',
        'long' => '116.7',
        'lat' => '4.1333',
      ],
      [
        'name' => 'Tana Tidung',
        'province_id' => '1',
        'region' => 'Kabupaten',
        'long' => '117.25',
        'lat' => '3.55',
      ],
      [
        'name' => 'Tarakan',
        'province_id' => '1',
        'region' => 'Kota',
        'long' => '117.63',
        'lat' => '3.3',
      ],
    ];
    District::insert($districts);
  }
}
